# Generated by Django 5.2.5 on 2025-08-21 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='SCHEDULED', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('SOLO', 'Solo Lesson'), ('PAIR', 'Pair Lesson'), ('GROUP', 'Group Lesson')], max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.term')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('FILL_IN', 'Fill-in')], max_length=10)),
                ('reason_for_absence', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.enrollment')),
                ('lesson_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.lessonsession')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Wednesday 4pm Advanced', max_length=200)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.coach')),
                ('members', models.ManyToManyField(to='scheduler.enrollment')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.term')),
            ],
        ),
        migrations.AddField(
            model_name='lessonsession',
            name='scheduled_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.scheduledgroup'),
        ),
    ]
