# Generated by Django 5.2.5 on 2025-08-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_lessonsession_enrollment_attendancerecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_understanding', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('NEEDS_REVIEW', 'Needs Review')], max_length=15)),
                ('topics_covered', models.TextField(blank=True, help_text='A brief summary of topics covered in the lesson.')),
                ('coach_comments', models.TextField(blank=True, help_text='Private notes for the next lesson.')),
                ('attendance_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='scheduler.attendancerecord')),
            ],
        ),
    ]
