# Generated by Django 5.2.5 on 2025-08-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_lessonnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_head_coach',
            field=models.BooleanField(default=False, help_text="Head coaches can view all other coaches' schedules."),
        ),
    ]
