# Generated by Django 5.2.5 on 2025-08-21 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_coach_is_head_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledgroup',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='scheduledgroup',
            name='start_time',
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.CharField(blank=True, help_text='e.g., 4G, 5P, etc.', max_length=10),
        ),
        migrations.CreateModel(
            name='ScheduledUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Year 4 Sports', max_length=200)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('students', models.ManyToManyField(to='scheduler.student')),
                ('time_slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.timeslot')),
            ],
        ),
        migrations.AddField(
            model_name='scheduledgroup',
            name='time_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduler.timeslot'),
        ),
    ]
