# Generated by Django 5.2.5 on 2025-08-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_coach_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('FILL_IN', 'Fill-in')], default='PENDING', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('lesson_session', 'enrollment')},
        ),
    ]
