# Generated by Django 5.2.5 on 2025-08-26 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_attendancerecord_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='email',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='reason_for_absence',
            field=models.CharField(blank=True, choices=[('SICK', 'Sick'), ('TEACHER_REFUSAL', 'Teacher Refusal'), ('CLASS_EVENT', 'Class Event'), ('CLASS_EMPTY', 'Class Empty'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lessonnote',
            name='attendance_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lessonnote', to='scheduler.attendancerecord'),
        ),
    ]
