# Generated by Django 5.2.5 on 2025-09-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_remove_coach_email_remove_coach_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'verbose_name': 'Coach', 'verbose_name_plural': 'Coaches'},
        ),
        migrations.AlterModelOptions(
            name='scheduledunavailability',
            options={'verbose_name': 'Scheduled Unavailability', 'verbose_name_plural': 'Scheduled Unavailabilities'},
        ),
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'verbose_name': 'School Class', 'verbose_name_plural': 'School Classes'},
        ),
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one term can be active at a time. This term will be used for CSV imports.'),
        ),
    ]
