# Generated by Django 5.2.5 on 2025-09-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='adjusted_target',
            field=models.IntegerField(default=8, editable=False, help_text='Calculated: target_lessons + lessons_carried_forward'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lessons_carried_forward',
            field=models.IntegerField(default=0, help_text='Lessons owed from previous term (+) or credit (-)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='target_lessons',
            field=models.IntegerField(default=8, help_text='Target lessons for this term'),
        ),
    ]
