# Generated by Django 5.2.5 on 2025-09-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_enrollment_adjusted_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('FILL_IN', 'Fill-in'), ('SICK_PRESENT', 'Sick but Present'), ('REFUSES_PRESENT', 'Present but Refuses')], default='PENDING', max_length=15),
        ),
    ]
