# Generated by Django 5.2.5 on 2025-09-18 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_add_sick_present_refuses_present_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oneoffevent',
            options={'ordering': ['-event_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='oneoffevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='oneoffevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduler.coach'),
        ),
        migrations.AddField(
            model_name='oneoffevent',
            name='end_date',
            field=models.DateField(blank=True, help_text='For multi-day events like camps', null=True),
        ),
        migrations.AddField(
            model_name='oneoffevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('PUBLIC_HOLIDAY', 'Public Holiday'), ('PUPIL_FREE_DAY', 'Pupil Free Day'), ('CAMP', 'Camp'), ('EXCURSION', 'Class Excursion'), ('INDIVIDUAL', 'Individual Students'), ('CUSTOM', 'Custom Event')], default='CUSTOM', max_length=20),
        ),
        migrations.AddField(
            model_name='oneoffevent',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Whether this event has been processed'),
        ),
        migrations.AddField(
            model_name='oneoffevent',
            name='year_levels',
            field=models.CharField(blank=True, help_text="Comma-separated year levels (e.g., '3,4,5')", max_length=50),
        ),
    ]
