# Generated by Django 5.2.5 on 2025-09-23 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_oneoffevent_options_oneoffevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='max_students_per_lesson',
            field=models.IntegerField(default=4, help_text='Maximum students this coach prefers per lesson'),
        ),
        migrations.AddField(
            model_name='coach',
            name='preferred_group_sizes',
            field=models.CharField(default='PAIR,GROUP', help_text='Comma-separated preferred group sizes (SOLO,PAIR,GROUP)', max_length=20),
        ),
        migrations.AddField(
            model_name='coach',
            name='specializes_advanced',
            field=models.BooleanField(default=False, help_text='Coach is effective with advanced students'),
        ),
        migrations.AddField(
            model_name='coach',
            name='specializes_beginner',
            field=models.BooleanField(default=True, help_text='Coach is effective with beginner students'),
        ),
        migrations.AddField(
            model_name='coach',
            name='specializes_intermediate',
            field=models.BooleanField(default=True, help_text='Coach is effective with intermediate students'),
        ),
        migrations.AddField(
            model_name='scheduledgroup',
            name='group_type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('PAIR', 'Pair'), ('GROUP', 'Group')], default='GROUP', help_text='Type of group (Solo, Pair, or Group)', max_length=5),
        ),
        migrations.AddField(
            model_name='scheduledgroup',
            name='max_capacity',
            field=models.IntegerField(default=4, help_text='Maximum number of students in this group'),
        ),
        migrations.AddField(
            model_name='scheduledgroup',
            name='preferred_size',
            field=models.IntegerField(default=3, help_text='Preferred number of students in this group'),
        ),
        migrations.AddField(
            model_name='scheduledgroup',
            name='target_skill_level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', help_text='Target skill level for this group', max_length=1),
        ),
        migrations.AddField(
            model_name='student',
            name='preferred_group_size',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('PAIR', 'Pair'), ('GROUP', 'Group')], default='GROUP', help_text='Preferred lesson group size', max_length=5),
        ),
        migrations.AddField(
            model_name='student',
            name='skill_level',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('A', 'Advanced')], default='B', help_text='Chess skill level: Beginner, Intermediate, or Advanced', max_length=1),
        ),
    ]
