# Generated by Django 5.2.5 on 2025-09-23 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_add_intelligent_slot_finder_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='preferred_group_size',
        ),
    ]
