# Generated by Django 5.2.5 on 2025-09-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0035_fix_current_group_exclusion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonnote',
            name='student_understanding',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('NEEDS_REVIEW', 'Needs Review')], max_length=500),
        ),
        migrations.AlterField(
            model_name='scheduledgroup',
            name='max_capacity',
            field=models.IntegerField(default=4, help_text='Maximum number of students in this group (auto-calculated based on group type)'),
        ),
        migrations.AlterField(
            model_name='scheduledgroup',
            name='preferred_size',
            field=models.IntegerField(default=3, help_text='Preferred number of students in this group (auto-calculated based on group type)'),
        ),
    ]
