# Generated by Django 5.2.5 on 2025-10-09 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0036_increase_student_understanding_field_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive students are removed from future lessons but keep historical records'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='withdrawal_date',
            field=models.DateField(blank=True, help_text='Date when student became inactive (optional)', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='withdrawal_reason',
            field=models.CharField(blank=True, help_text='Reason for withdrawal (optional)', max_length=200),
        ),
    ]
