# Generated by Django 5.2.5 on 2025-10-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0037_add_enrollment_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('FILL_IN', 'Fill-in'), ('FILL_IN_ABSENT', 'Fill-in Absent'), ('SICK_PRESENT', 'Sick but Present'), ('REFUSES_PRESENT', 'Present but Refuses')], default='PENDING', max_length=15),
        ),
    ]
