# Generated by Django 5.2.5 on 2025-10-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0039_curriculumlevel_curriculumtopic_studentprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='reason_for_absence',
            field=models.CharField(blank=True, choices=[('SICK', 'Sick'), ('TEACHER_REFUSAL', 'Teacher Refusal'), ('CLASS_EVENT', 'Class Event'), ('CLASS_EMPTY', 'Class Empty'), ('COACH_TOURNAMENT', 'Coach at Tournament'), ('COACH_SICK', 'Coach Sick'), ('SPECIALIST_CLASS', 'Specialist Class'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
