# Generated by Django 5.2.5 on 2025-10-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0040_add_coach_absence_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oneoffevent',
            name='event_type',
            field=models.CharField(blank=True, choices=[('PUBLIC_HOLIDAY', 'Public Holiday'), ('PUPIL_FREE_DAY', 'Pupil Free Day'), ('CAMP', 'Camp'), ('EXCURSION', 'Class Excursion'), ('INDIVIDUAL', 'Individual Students'), ('COACH_AWAY', 'Coach Away'), ('CUSTOM', 'Custom Event')], default='CUSTOM', max_length=20),
        ),
    ]
